level: "debug"
store: "F:\\data"
cron: "* * * * *"
backup:
- type: mysql
  host: 192.168.52.147
  port: 3306
  user: root
  password: root
- type: pg
  host: 192.168.52.147
  port: 5432
  user: postgres
  password: root
- type: mongo
  host: 192.168.52.147
  port: 27017
  user: ""
  password: ""
- type: scp
  user: root 
  password: root
  host: 192.168.52.147
  port: 22
  fromPath: /tmp/scp